# Use the official Golang image as the base image
FROM golang:1.24 as builder

# Set the working directory inside the container
WORKDIR /app

# Copy go.mod and go.sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the rest of the application code
COPY . .

# Build the application
RUN go build -o smartlab-backend .

# Expose the port the application runs on
EXPOSE 8080

# Command to run the application
CMD ["/app/smartlab-backend"]